// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: perception/proto/perception_config.proto

#ifndef PROTOBUF_INCLUDED_perception_2fproto_2fperception_5fconfig_2eproto
#define PROTOBUF_INCLUDED_perception_2fproto_2fperception_5fconfig_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "perception/proto/ogm_config.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_perception_2fproto_2fperception_5fconfig_2eproto 

namespace protobuf_perception_2fproto_2fperception_5fconfig_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_perception_2fproto_2fperception_5fconfig_2eproto
namespace perception {
class PerceptionConfig;
class PerceptionConfigDefaultTypeInternal;
extern PerceptionConfigDefaultTypeInternal _PerceptionConfig_default_instance_;
}  // namespace perception
namespace google {
namespace protobuf {
template<> ::perception::PerceptionConfig* Arena::CreateMaybeMessage<::perception::PerceptionConfig>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace perception {

// ===================================================================

class PerceptionConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:perception.PerceptionConfig) */ {
 public:
  PerceptionConfig();
  virtual ~PerceptionConfig();

  PerceptionConfig(const PerceptionConfig& from);

  inline PerceptionConfig& operator=(const PerceptionConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PerceptionConfig(PerceptionConfig&& from) noexcept
    : PerceptionConfig() {
    *this = ::std::move(from);
  }

  inline PerceptionConfig& operator=(PerceptionConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PerceptionConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PerceptionConfig* internal_default_instance() {
    return reinterpret_cast<const PerceptionConfig*>(
               &_PerceptionConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(PerceptionConfig* other);
  friend void swap(PerceptionConfig& a, PerceptionConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PerceptionConfig* New() const final {
    return CreateMaybeMessage<PerceptionConfig>(NULL);
  }

  PerceptionConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PerceptionConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PerceptionConfig& from);
  void MergeFrom(const PerceptionConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PerceptionConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .perception.OgmConfig ogm_config = 1;
  bool has_ogm_config() const;
  void clear_ogm_config();
  static const int kOgmConfigFieldNumber = 1;
  private:
  const ::perception::OgmConfig& _internal_ogm_config() const;
  public:
  const ::perception::OgmConfig& ogm_config() const;
  ::perception::OgmConfig* release_ogm_config();
  ::perception::OgmConfig* mutable_ogm_config();
  void set_allocated_ogm_config(::perception::OgmConfig* ogm_config);

  // @@protoc_insertion_point(class_scope:perception.PerceptionConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::perception::OgmConfig* ogm_config_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_perception_2fproto_2fperception_5fconfig_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PerceptionConfig

// .perception.OgmConfig ogm_config = 1;
inline bool PerceptionConfig::has_ogm_config() const {
  return this != internal_default_instance() && ogm_config_ != NULL;
}
inline const ::perception::OgmConfig& PerceptionConfig::_internal_ogm_config() const {
  return *ogm_config_;
}
inline const ::perception::OgmConfig& PerceptionConfig::ogm_config() const {
  const ::perception::OgmConfig* p = ogm_config_;
  // @@protoc_insertion_point(field_get:perception.PerceptionConfig.ogm_config)
  return p != NULL ? *p : *reinterpret_cast<const ::perception::OgmConfig*>(
      &::perception::_OgmConfig_default_instance_);
}
inline ::perception::OgmConfig* PerceptionConfig::release_ogm_config() {
  // @@protoc_insertion_point(field_release:perception.PerceptionConfig.ogm_config)
  
  ::perception::OgmConfig* temp = ogm_config_;
  ogm_config_ = NULL;
  return temp;
}
inline ::perception::OgmConfig* PerceptionConfig::mutable_ogm_config() {
  
  if (ogm_config_ == NULL) {
    auto* p = CreateMaybeMessage<::perception::OgmConfig>(GetArenaNoVirtual());
    ogm_config_ = p;
  }
  // @@protoc_insertion_point(field_mutable:perception.PerceptionConfig.ogm_config)
  return ogm_config_;
}
inline void PerceptionConfig::set_allocated_ogm_config(::perception::OgmConfig* ogm_config) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(ogm_config_);
  }
  if (ogm_config) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      ogm_config = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, ogm_config, submessage_arena);
    }
    
  } else {
    
  }
  ogm_config_ = ogm_config;
  // @@protoc_insertion_point(field_set_allocated:perception.PerceptionConfig.ogm_config)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace perception

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_perception_2fproto_2fperception_5fconfig_2eproto
