// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: map/proto/pnc_path_config.proto

#ifndef PROTOBUF_INCLUDED_map_2fproto_2fpnc_5fpath_5fconfig_2eproto
#define PROTOBUF_INCLUDED_map_2fproto_2fpnc_5fpath_5fconfig_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_map_2fproto_2fpnc_5fpath_5fconfig_2eproto 

namespace protobuf_map_2fproto_2fpnc_5fpath_5fconfig_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_map_2fproto_2fpnc_5fpath_5fconfig_2eproto
namespace map {
class PncPathConfig;
class PncPathConfigDefaultTypeInternal;
extern PncPathConfigDefaultTypeInternal _PncPathConfig_default_instance_;
}  // namespace map
namespace google {
namespace protobuf {
template<> ::map::PncPathConfig* Arena::CreateMaybeMessage<::map::PncPathConfig>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace map {

// ===================================================================

class PncPathConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:map.PncPathConfig) */ {
 public:
  PncPathConfig();
  virtual ~PncPathConfig();

  PncPathConfig(const PncPathConfig& from);

  inline PncPathConfig& operator=(const PncPathConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PncPathConfig(PncPathConfig&& from) noexcept
    : PncPathConfig() {
    *this = ::std::move(from);
  }

  inline PncPathConfig& operator=(PncPathConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PncPathConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PncPathConfig* internal_default_instance() {
    return reinterpret_cast<const PncPathConfig*>(
               &_PncPathConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(PncPathConfig* other);
  friend void swap(PncPathConfig& a, PncPathConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PncPathConfig* New() const final {
    return CreateMaybeMessage<PncPathConfig>(NULL);
  }

  PncPathConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PncPathConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PncPathConfig& from);
  void MergeFrom(const PncPathConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PncPathConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double search_radius = 1;
  void clear_search_radius();
  static const int kSearchRadiusFieldNumber = 1;
  double search_radius() const;
  void set_search_radius(double value);

  // double search_theta_diff = 2;
  void clear_search_theta_diff();
  static const int kSearchThetaDiffFieldNumber = 2;
  double search_theta_diff() const;
  void set_search_theta_diff(double value);

  // double look_backward_distance = 3;
  void clear_look_backward_distance();
  static const int kLookBackwardDistanceFieldNumber = 3;
  double look_backward_distance() const;
  void set_look_backward_distance(double value);

  // double look_forward_distance = 4;
  void clear_look_forward_distance();
  static const int kLookForwardDistanceFieldNumber = 4;
  double look_forward_distance() const;
  void set_look_forward_distance(double value);

  // @@protoc_insertion_point(class_scope:map.PncPathConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double search_radius_;
  double search_theta_diff_;
  double look_backward_distance_;
  double look_forward_distance_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_map_2fproto_2fpnc_5fpath_5fconfig_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PncPathConfig

// double search_radius = 1;
inline void PncPathConfig::clear_search_radius() {
  search_radius_ = 0;
}
inline double PncPathConfig::search_radius() const {
  // @@protoc_insertion_point(field_get:map.PncPathConfig.search_radius)
  return search_radius_;
}
inline void PncPathConfig::set_search_radius(double value) {
  
  search_radius_ = value;
  // @@protoc_insertion_point(field_set:map.PncPathConfig.search_radius)
}

// double search_theta_diff = 2;
inline void PncPathConfig::clear_search_theta_diff() {
  search_theta_diff_ = 0;
}
inline double PncPathConfig::search_theta_diff() const {
  // @@protoc_insertion_point(field_get:map.PncPathConfig.search_theta_diff)
  return search_theta_diff_;
}
inline void PncPathConfig::set_search_theta_diff(double value) {
  
  search_theta_diff_ = value;
  // @@protoc_insertion_point(field_set:map.PncPathConfig.search_theta_diff)
}

// double look_backward_distance = 3;
inline void PncPathConfig::clear_look_backward_distance() {
  look_backward_distance_ = 0;
}
inline double PncPathConfig::look_backward_distance() const {
  // @@protoc_insertion_point(field_get:map.PncPathConfig.look_backward_distance)
  return look_backward_distance_;
}
inline void PncPathConfig::set_look_backward_distance(double value) {
  
  look_backward_distance_ = value;
  // @@protoc_insertion_point(field_set:map.PncPathConfig.look_backward_distance)
}

// double look_forward_distance = 4;
inline void PncPathConfig::clear_look_forward_distance() {
  look_forward_distance_ = 0;
}
inline double PncPathConfig::look_forward_distance() const {
  // @@protoc_insertion_point(field_get:map.PncPathConfig.look_forward_distance)
  return look_forward_distance_;
}
inline void PncPathConfig::set_look_forward_distance(double value) {
  
  look_forward_distance_ = value;
  // @@protoc_insertion_point(field_set:map.PncPathConfig.look_forward_distance)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace map

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_map_2fproto_2fpnc_5fpath_5fconfig_2eproto
